credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrator
      password: $2b$12$UOaapfn2B7uW4LRjhRmfNeQX0k4wmEkwW1IBmwtjkFwimpMOwlkHi
    analyst1:
      email: analyst1@team.com
      failed_login_attempts: 0
      logged_in: false
      name: Analyst 1
      password: temppass123
      role: viewer
    analyst2:
      email: analyst2@team.com
      failed_login_attempts: 0
      logged_in: false
      name: Analyst 2
      password: temppass123
      role: viewer
    analyst3:
      email: analyst3@team.com
      failed_login_attempts: 0
      logged_in: false
      name: Analyst 3
      password: temppass123
      role: viewer
    analyst4:
      email: analyst4@team.com
      failed_login_attempts: 0
      logged_in: false
      name: Analyst 4
      password: temppass123
      role: viewer
cookie:
  expiry_days: 30
  key: recession_prediction_app
  name: recession_app_cookie
preauthorized:
  emails: []
